import { useEffect, useState } from "react";
import { BriefcaseBusiness, Menu, X } from "lucide-react";

export default function Navbar({ lang, setLang, path, navigate }) {
  const [open, setOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const L = lang === "fr" ? { home: "Accueil", about: "À propos", experience: "Parcours", contact: "Contact", talk: "Travaillons ensemble", menu: "Ouvrir le menu" } : { home: "Home", about: "About", experience: "Experience", contact: "Contact", talk: "Let's work together", menu: "Open menu" };
  const items = [["/", L.home], ["/about", L.about], ["/experience", L.experience], ["/contact", L.contact]];
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 12); onScroll(); window.addEventListener("scroll", onScroll); return () => window.removeEventListener("scroll", onScroll); }, []);
  const go = (href) => { navigate(href); setOpen(false); };
  const itemClass = (href) => `rounded-lg px-3 py-2 text-sm font-semibold transition ${path === href ? "bg-blue-50 text-blue-700" : "text-slate-600 hover:bg-slate-100 hover:text-blue-600"}`;

  return <header className={`sticky top-0 z-50 border-b transition-all duration-300 ${scrolled ? "border-slate-200/80 bg-white/90 shadow-sm backdrop-blur-xl" : "border-transparent bg-white/75 backdrop-blur-md"}`}><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><a href="/" onClick={(e) => { e.preventDefault(); go("/"); }} className="group flex items-center gap-3" aria-label="Julien Zigabe home"><span className="flex size-10 items-center justify-center rounded-lg bg-slate-950 text-white transition group-hover:bg-blue-600"><BriefcaseBusiness size={18} /></span><span><span className="block font-bold tracking-tight text-slate-950">Julien <span className="text-orange-500">Zigabe</span></span><span className="hidden text-[10px] font-bold uppercase tracking-[0.18em] text-slate-500 sm:block">Consultant · Speaker · Builder</span></span></a><nav className="hidden items-center gap-1 lg:flex" aria-label="Primary">{items.map(([href, label]) => <a key={href} href={href} onClick={(e) => { e.preventDefault(); go(href); }} className={itemClass(href)} aria-current={path === href ? "page" : undefined}>{label}</a>)}</nav><div className="flex items-center gap-2"><div className="flex rounded-lg border border-slate-200 bg-slate-100 p-1">{["en", "fr"].map((code) => <button key={code} type="button" onClick={() => { setLang(code); localStorage.setItem("lang", code); }} className={`rounded-md px-3 py-1.5 text-xs font-bold ${lang === code ? "bg-white text-slate-950 shadow-sm" : "text-slate-500"}`}>{code.toUpperCase()}</button>)}</div><a href="/contact" onClick={(e) => { e.preventDefault(); go("/contact"); }} className="hidden rounded-lg bg-orange-500 px-4 py-2 text-sm font-bold text-white transition hover:bg-orange-600 sm:inline-flex">{L.talk}</a><button type="button" onClick={() => setOpen((value) => !value)} className="inline-flex size-10 items-center justify-center rounded-lg border border-slate-200 text-slate-800 lg:hidden" aria-label={L.menu}>{open ? <X size={20} /> : <Menu size={20} />}</button></div></div>{open && <nav className="grid gap-1 border-t border-slate-100 bg-white px-5 py-4 lg:hidden">{items.map(([href, label]) => <a key={href} href={href} onClick={(e) => { e.preventDefault(); go(href); }} className={itemClass(href)}>{label}</a>)}</nav>}</header>;
}
